ProFive/ProFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from ProFive_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'app/', include('ProFive_app.urls')),
    url(r'logout/$', views.user_logout, name = 'logout'),
    url(r'special/$', views.special)
]

ProFive/ProFive_app/urls.py
from django.conf.urls import include, url
from ProFive_app import views

# required for templates
app_name = 'ProFive_app'

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'register/$', views.register, name='register'),
    url(r'user_login/$',views.user_login, name='user_login')
]

ProFive/ProFive_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    """ User profile default inherited from the django contrib and extended """

    user = models.OneToOneField(User, on_delete=models.PROTECT)
    #added fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def str(self):
        return self.user.user.username

class BankAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    bankName = models.CharField(max_length = 100)
    accountNameUser = models.CharField(max_length = 100)
    ibanAccount = models.CharField(max_length = 100)


    def str(self):
        return 'Account "{}": iban {}, bank {}'.format(self.accountNameUser, self.ibanAccount, self.bankName)



class UserLoginInfo(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    loginInfo = models.DateTimeField()

ProFive/ProFive_app/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username','email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

ProFive/ProFive_app/views.py
from django.shortcuts import render
from ProFive_app.forms import UserForm, UserProfileInfoForm
from ProFive_app.models import User, UserProfileInfo
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.


def index(request):
    return render(request, 'ProFive_app/index.html')



def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        userProfile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and userProfile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = userProfile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors, userProfile_form.errors)
    else:
        user_form = UserForm()
        userProfile_form = UserProfileInfoForm()

    return render(request, 'ProFive_app/registration.html',
                  {'registered': registered, 'user_form': user_form, 'profile_form': userProfile_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("someone tried to login and failed")
            print('Username {} and PW {}'.format(username, password))
    else:
        return render(request, 'ProFive_app/login.html', {})


@login_required
def special(request):
    return HttpResponse('Hey youre logged in ! Yo')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

ProFive/templates/ProFive_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-ligh">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <ul class="nav navbar-nav">

        <li class="nav-item"><a class="nav-link" href="{% url 'ProFive_app:register' %}">Register</a></li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout'%}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ProFive_app:user_login'%}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}

    {% endblock %}

  </div>
</body>

</html>

ProFive/templates/ProFive_app/index.html
{%extends "ProFive_app/base.html" %}
{% block body_block%}

<div class="jumbotron">
  <h1>Home page</h1>
</div>

{% endblock %}

ProFive/templates/ProFive_app/login.html
{% extends 'ProFive_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login: </h1>
  <form class="" action="{% url 'ProFive_app:user_login' %}" method="post">
    {% csrf_token %}

      <img class="img-thumbnail col-4 offset-4" src="https://i.pinimg.com/345x/90/6f/85/906f852b53d5c3dc5bf98aa74d2aca26.jpg" alt="">
      <h2>Login</h2>
      <div class="form-group form-group-labelhandling">
        <input type="text" class="form-control" id="username" aria-describedby="userHelp" placeholder="" name="username">
        <label for="username">Username or email</label>
        <small id="userHelp" class="form-text text-muted">Type your username or email in.</small>
      </div>
      <div class="form-group form-group-labelhandling">
        <input id="password" class="form-control" type="password" name="password" placeholder="">
        <label for="password">Password</label>
      </div>
      <input class="btn btn-primary" type="submit" name="" value="Go!">
  </form>

</div>
{% endblock %}

ProFive/templates/ProFive_app/registration.html
{% extends "ProFive_app/base.html" %}
{% load staticfiles %}

{% block body_block%}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
    <h1>Register here</h1>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input class="btn btn-primary" type="submit" name="" value="Go!">
    </form>


  {% endif %}

</div>
{% endblock %}